### ISSUE TITLE
Minimum requirements for audio / video

### ISSUE THREAD

**Issue by KnutSchrader** [AVnu/tsn-doc#1]
Hello,
I would like to know the minimum requirements regarding audio and or video.
Is a Coffee Lake based processor necessary for video, or could an older processor be sufficient?
I assume the h264 decoder is the necessary part, in order to get avb video running.
Thanks,

**Comment by aguedes** [comment]
Hi, Coffee Lake isn't a requirement. You could use any processor.

**Comment by aguedes** [comment]
Re-reading https://tsn.readthedocs.io/en/latest/avb.html#system-requirements, I can see where this question might have come from :)

@edersondisouza, could you please fix the System Requirements section so we clearly state what is a requirement and what was utilized to validate the commands?

**Comment by edersondisouza** [comment]
#4

**Comment by aguedes** [comment]
Hi @KnutSchrader, I believe we addressed this issue so I'm closing it. Feel free to re-open it in case something is still not clear.
