### ISSUE TITLE
PHC2SYS option step_threshold and transportSpecific

### ISSUE THREAD

**Issue by elabbing** [AVnu/tsn-doc#10]
Hi, my `uname -a` is
`Linux ubuntu 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
Could you help me, please?

I'm trying to synchronize time with LinuxPTP v1.8, and in ptp4l option
`--step_threshold=1`
don't work, but
`step_threshold=1`
seems ok (I don't know how to check this..)

In `phc2sys` command, options
`step_threshold`
don't exist, maybe I have to use `-S` option?

More, `transportSpecific` option don't exist in `phc2sys` command.
Can I skip it?

Many thanks

**Comment by aguedes** [comment]
I believe the long option support was added after v1.8. That's probably why it's not working for you.

To work this around in ptp4l, try setting `step_threshold 1` in `gPTP.cfg`. For `phc2sys`, yes the `-S` should work.

**Comment by vedangpatel1** [comment]
When phc2sys tries to communicate to ptp4l, it sets the value specified in the `transportSpecific` in the ptp_header (struct defined in msg.h). ptp4l will drop the packet if the value is not present. So, you will not be able to communicate with ptp4l if you do not have it set. I would recommend you use a later version of linuxptp to resolve this issue.

**Comment by aguedes** [comment]
This issue seems to be sorted out already so I'm closing it for now. We can reopen it if otherwise.
