### ISSUE TITLE
Media Clock Recovery

### ISSUE THREAD

**Issue by blueberrypie** [Avnu/tsn-doc#22]
Hello, 

I want to understand how the media clock recovery is addressed on the listener side. As per the section 3.3 (Figuire 10) of Avnu document [https://avnu.org/wp-content/uploads/2014/05/AVnu_SWAPIs-v1.3-SWAVI-Updates_Final_Approved_Clean.pdf](https://avnu.org/wp-content/uploads/2014/05/AVnu_SWAPIs-v1.3-SWAVI-Updates_Final_Approved_Clean.pdf), we need to do media clock recovery using the presentation time in AAF frames(or CRF frames) and adjust the DAC's clock through  HW clock recovery circuit. 

I am not able to understand how this is achieved using the ALSA AAF/ Gstreamer AVTP plugins. 
Could anyone please explain this?

Many thanks

**Comment by edersondisouza** [comment]
Hi @blueberrypie,

What both plugins basically do is:
  - Assume gPTP time is synchronised;
  - Assume CLOCK_REALTIME is synchronised with gPTP time (with the TAI coordinate difference considered);
  - Retrieve the presentation timestamp from the AVTP DU;
  - Convert presentation timestamp back to gPTP time;
  - Leverage ALSA/GStreamer infra to present data on presentation timestamp (usually a timer set to expire at presentation timestamp on CLOCK_REALTIME).

Does that explain you question, or is there any point missing?

**Comment by blueberrypie** [comment]
Hi @edersondisouza, 

Thanks for the response. 

One thing I am not still very clear about the following. 
how the CODEC's clock is synchronized. Like ADC/DAC?
Even though we set the CODEC to the same sample rate as per the AVTP frames. (like 48k). Due to some minor errors in the crystal clock which is used for generating CODEC clocks, may drift over time. 

From my understanding, we need to do media clock recovery using hardware clock circuit ICs (like [CS2100](https://www.mouser.in/applications/ethernet-avb-networks/)) by feeding the presentation timestamps. The clock generated from the media clock recovery should be used for CODECs instead of the local crystal clock to avoid this drift. 

As we are not doing any of that when we use these ALSA/Gstremer, I was not clear, how this drift is not happening in the long run.  ALSA/Gstreamer do some ASRC internally to take care of these drifts?

Many Thanks.

**Comment by edersondisouza** [comment]
Not sure if I got your point: yes, clocks do diverge. But both ALSA and GStreamer AVTP plugins assume that the clock they are using (for instance, system CLOCK_REALTIME) is synchronised using gPTP (IEEE 802.1AS). So, if you have a different media clock, for example in your audio card, it is then your application responsibility to ensure this clock is also in sync with the network one. I believe at least GStreamer has some provision for this cross time-stamping, but the plugins are they are now don't care about that - they just assume you're using the right clock.
(And sorry for the late reply.)

**Comment by blueberrypie** [comment]
Thanks a lot. I understand that if the media card uses a different clock, we need to sync that separately.
